### ISSUE TITLE
alma sync

### ISSUE THREAD

**Issue by roxannewyns** [libis/lovaniensia#4]
Ik heb een aantal Alma objecten proberen te synchroniseren en krijg deze foutmelding (e.g; 9992225788701488|9992225262401488|9992243101701488

![image](https://user-images.githubusercontent.com/3798589/31935640-9de479c6-b8af-11e7-8ea1-0e4897b17134.png)

**Comment by JorisLambrechts** [comment]
Er ontbreken nog een aantal metadata velden

**Comment by JorisLambrechts** [comment]
lectio metadatavelden toegevoegd aan item type physical object (maar maakt niet uit welk type)
